
#:import FadeTransition kivy.uix.screenmanager.FadeTransition
#:import random random.random
#:import Factory kivy.factory.Factory
#:import os os

RelativeLayout:
    MyScreenManager:
        id: sm
        #size_hint: 1, .8
        transition: FadeTransition()
        FirstScreen:
            id: first_screen
        SettingsScreen:
            id: settings_screen
    
    FloatLayout:
        Label: 
            text: ''#'teste'
            color: 0, 1, 0, 1

